### ISSUE TITLE
Error executing lua callback

### ISSUE THREAD

**Issue by mauroapo** [jonathanmorris180/salesforce.nvim#40] opened 2024-06-16 23:55 UTC
## Steps to reproduce

1. I opened nvim in my Apex Class, selected the default org and I got this error after a SalesforcePushToOrg command
2. Then I saw the error below
3. Error
`
Error executing Lua callback: ...Local\nvim-data\plugged\plenary.nvim/lua/plenary/job.lua:406: Failed to spawn process: {
  _additional_on_exit_callbacks = {},
  _shutdown_check = <userdata 1>,
  _stderr_results = {},
  _stdout_results = {},
  _user_on_exit = <function 1>,
  _user_on_stderr = <function 2>,
  _user_on_stdout = <function 3>,
  args = { "project", "deploy", "start", "--json", "-o", "mauro.apo123@resourceful-panda-v0tc3s.com", "-d", "C:\\Users\\Acer\\Documents\\Projetos\\Salesforce\\ResourcefulPanda\\force-app\\main\\default\\classes\\WarehouseCalloutService.cls" },
  command = "sf",
  enable_handlers = true,
  enable_recording = true,
  interactive = true,
  pid = "ENOENT: no such file or directory",
  stderr = <userdata 2>,
  stdin = <userdata 3>,
  stdout = <userdata 4>,
  user_data = {},
  <metatable> = <1>{
    __index = <table 1>,
    _create_uv_options = <function 4>,
    _execute = <function 5>,
    _pipes_are_closed = <function 6>,
    _prepare_pipes = <function 7>,
    _reset = <function 8>,
    _shutdown = <function 9>,
    _stop = <function 10>,
    add_on_exit_callback = <function 11>,
    after = <function 12>,
    after_failure = <function 13>,
    after_success = <function 14>,
    and_then = <function 15>,
    and_then_on_failure = <function 16>,
    and_then_on_failure_wrap = <function 17>,
    and_then_on_success = <function 18>,
    and_then_on_success_wrap = <function 19>,
    and_then_wrap = <function 20>,
    chain = <function 21>,
    chain_status = <function 22>,
    co_wait = <function 23>,
    is_job = <function 24>,
    is_running = <function 25>,
    join = <function 26>,
    new = <function 27>,
    pid = <function 28>,
    result = <function 29>,
    send = <function 30>,
    shutdown = <function 31>,
    start = <function 32>,
    stderr_result = <function 33>,
    sync = <function 34>,
    wait = <function 35>
  }
}
stack traceback:
	...Local\nvim-data\plugged\plenary.nvim/lua/plenary/job.lua:406: in function '_execute'
	...Local\nvim-data\plugged\plenary.nvim/lua/plenary/job.lua:449: in function 'start'
	[string ":lua"]:27: in function 'debug_job'
	[string ":lua"]:31: in function <[string ":lua"]:30>
stack traceback:
	[C]: in function 'error'
	...Local\nvim-data\plugged\plenary.nvim/lua/plenary/job.lua:406: in function '_execute'
	...Local\nvim-data\plugged\plenary.nvim/lua/plenary/job.lua:449: in function 'start'
	[string ":lua"]:27: in function 'debug_job'
	[string ":lua"]:31: in function <[string ":lua"]:30>`                            
## Expected behavior

Expected the class to be pushed to the org

## Environment

- NVIM v0.10.0
- salesforce.nvim version: [e.g. latest]
- Plugin clash: [e.g. Telescope float window / lsp diagnostic]

## Other comments
I did the command below inside of the same terminal I was executing the :SalesforcePushToOrg command

:terminal sf project deploy start --json -o mauro.apo123@resourceful-panda-v0tc3s.com -d C:\Users\Acer\Documents\Projetos\Salesforce\ResourcefulPanda\force-app\main\default\classes\WarehouseCalloutService.cls

and it worked fine

**Comment by jonathanmorris180** [comment] 2024-06-19 04:21
Hi @mauroapo, it looks like the issue is occurring because the file path isn't getting resolved correctly (it seems double backslashes are getting added). It's looking for `C:\\Users\\Acer\\Documents\\Projetos\\Salesforce\\ResourcefulPanda\\force-app\\main\\default\\classes\\WarehouseCalloutService.cls`, which results in `ENOENT: no such file or directory`. The code that retrieves the file path is [here](https://github.com/jonathanmorris180/salesforce.nvim/blob/main/lua/salesforce/file_manager.lua#L242). Could you please run the following in your Neovim command line and let me know what they print?

```
:lua print(vim.fn.expand("%:p"))
```
```
:lua print(vim.fs.normalize(vim.fn.expand("%:p")))
```

**Comment by jonathanmorris180** [comment] 2024-06-20 04:17
@mauroapo Can you please try changing the `sf_executable` to `sf.cmd` in your configuration of salesforce.nvim as proposed [here](https://github.com/jonathanmorris180/salesforce.nvim/issues/13#issuecomment-1921936817)? I believe this may be the fix (though theoretically it should detect the OS and update the executable accordingly, so I'm not sure why it didn't do this in your case).

**Comment by jonathanmorris180** [comment] 2024-06-22 03:02
@mauroapo Did you try the fix above?

**Comment by mauroapo** [comment] 2024-06-22 13:48
Hello, I'm sorry for the delay. It has been a busy week.
I did the change as requested but the issue persist. Here are the steps I did:

1 - opened the salesforce/config.lua file
2 - change the sf_executable to sf.cmd
3 - opened the salesforce file I want to push with nvim
4 - did the SalesforcePushToOrgCommand

![image](https://github.com/jonathanmorris180/salesforce.nvim/assets/49110280/d9a07314-b127-4844-8baa-a25fbb7a89a2)

Then I tried changing the `executable` variable inside the lua files. And it worked as expected. 

![image](https://github.com/jonathanmorris180/salesforce.nvim/assets/49110280/e50b2037-184a-41a4-b56f-02a28695c4e9)

I added all the changes to https://github.com/mauroapo/salesforce.nvim/tree/plugin-fix-windows for you to check. In it you'll see the changes in the config.lua, that didn't solve the issue, and the changes for file_manager.lua and diff.lua, that solved the issue.

**Comment by jonathanmorris180** [comment] 2024-06-25 04:33
Thanks for that info @mauroapo. It looks like there's a bug in the code that results in the executable not being recognized because of the order in which things get loaded on startup. Can you please let me know what prints in your terminal with the following command? I think I have a good way to solve this issue, but I want to check that it will be compatible with Windows first:

```
:lua print(vim.fn.fnamemodify(vim.fn.exepath("sf"), ":t"))
```

**Comment by mauroapo** [comment] 2024-06-25 10:44
Hello @jonathanmorris180, after executing the command this was the return:
![image](https://github.com/jonathanmorris180/salesforce.nvim/assets/49110280/34d8396c-c134-452a-9068-5102d0e8a686)
I hope it helps :)

**Comment by jonathanmorris180** [comment] 2024-06-26 03:54
Hi @mauroapo, I have added a fix for this in #41. Can you please pull down the [fix/issue-40](https://github.com/jonathanmorris180/salesforce.nvim/tree/fix/issue-40) branch and try it out? You would have to specify the branch in your plugin manager and possibly reinstall the plugin using that branch. After you have confirmed that it's working for you, I'll merge it into main.

**Comment by jonathanmorris180** [comment] 2024-06-28 19:06
Hi @mauroapo, were you able to try out the fix from #41?

**Comment by mauroapo** [comment] 2024-06-30 13:01
Hi, I'm using vim-plug. How can I specify the branch in it?

**Comment by mauroapo** [comment] 2024-07-04 11:13
@jonathanmorris180 just tested the changes. It is working well

**Closed** 2024-07-07 15:52 UTC
Labels: bug
